# Generated by Django 3.0.8 on 2021-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(blank='null', upload_to='satic/img'),
        ),
    ]
