# Generated by Django 3.0.8 on 2021-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(upload_to='satic/img'),
        ),
    ]
