# Generated by Django 3.0.8 on 2021-04-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210410_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(upload_to='./static/img'),
        ),
    ]
