# Generated by Django 3.0.8 on 2021-04-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210410_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tumbnail',
        ),
    ]
