# Generated by Django 3.0.8 on 2021-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_tumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
