# Generated by Django 3.0.5 on 2021-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
