# Generated by Django 3.0 on 2021-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210728_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
