# Generated by Django 3.0.5 on 2021-07-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
